//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Entry_id { get; set; }
        public Nullable<int> B_ID { get; set; }
        public Nullable<int> Total_Price { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
