//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public Nullable<int> D_ID { get; set; }
        public Nullable<int> Disease_ID { get; set; }
        public Nullable<int> LR_ID { get; set; }
        public Nullable<int> Room_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Lab_Report Lab_Report { get; set; }
        public virtual Room Room { get; set; }
    }
}
